name: Auto approve PRs by sideborg

# Trigger the workflow on pull request
on:
  pull_request

jobs:
  autoapprove:
    name: Auto Approve a PR by sideborg
    runs-on: ubuntu-latest
    steps:
      - name: Auto approve
        uses: hmarr/auto-approve-action@v2.0.0
        # Perform the auto approve action only when the PR is raised by sideborg
        if: github.actor == 'sideborg'
        with:
          github-token: ${{ secrets.GH_TOKEN }}
